server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/test123?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1q2w3e4r
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

jwt:
  access-token:
    name: access-token
    secret: accessSecret
    expiration: 2592000000
  refresh-token:
    name: refresh-token
    secret: refreshSecret
    expiration: 2592000000
front:
  url: "*"